### ISSUE TITLE
Error occurs when loading a feed which doesn't have 'station_information'

### ISSUE THREAD

**Issue by Kanahiro** [hiskoh/GBFS-NOW#1]
Thanks for the interesting plugin. I've tried and found a tiny bug.
Running on Window10 64bit QGIS 3.26 but aparrently it is not conserned to system enviroments.

1. I selected the following feed,

![dialog](https://user-images.githubusercontent.com/20744195/176190430-9fafa24b-af62-466c-9b75-3626d134a445.png)

2. clicked `View GBFS`, then error occured.

```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' 
Traceback (most recent call last):
  File "C:\Users/kiguchi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GBFS-NOW\gbfs_now_dockwidget.py", line 123, in view_gbfs_dataset
    station_info_url = self.get_gbfs_each_url('station_information')
  File "C:\Users/kiguchi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GBFS-NOW\gbfs_now_dockwidget.py", line 147, in get_gbfs_each_url
    return file_url + '?acl:consumerKey=' + self.token.text()
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This is caused by that `Bird Aleandria` doesn't have 'station_information' and then `file_url` is None.
In the specification, it seems that sometimes a feed doesn't have `station_information` (and also `station_status`) on dockless services.

**Comment by hiskoh** [comment]
Thank you for your comment.

As you pointed out, I haven't done the error handling when selecting GBFS for dockless service.

Besides , I haven't done error handling  when selecting an older-version-GBFS.

I'll correct both of these issues.

**Comment by hiskoh** [comment]
I’ve corrected the points you have pointed out.

https://github.com/hiskoh/GBFS-NOW/commit/a093839c0f697d67065aaf0f3c3770bd88ad0513
