### ISSUE TITLE
Getting data from a GBFS

### ISSUE THREAD

**Issue by MonsieurJ42** [hiskoh/GBFS-NOW#2]
Hello,

Your plugin seem to be very cool, bu I can get it to load my GBFS.json, neither I can get the plugin to load data from the GBFS GitHub "system.csv" file. 
I made some test around the proxy but it  don't seem to be that.

Is there there an issue with the 3.28 version of QGIS ? 
[log_python_GBFS_now.txt](https://github.com/hiskoh/GBFS-NOW/files/12016235/log_python_GBFS_now.txt)

**Comment by hiskoh** [comment]
Thanks for getting back to me. And I am really sorry for the late reply.

I tried with 3.28 on my PC and could not reproduce that error. So I have stopped because I am unable to investigate the cause. Are you still getting the same error?

**Comment by MonsieurJ42** [comment]
I did not test it since then. Your message made me go back to your extension and now it work. Probably a problem with our GBFS.
Great work !
